### ISSUE TITLE
Configuration file on root path of the project

### ISSUE THREAD

**Issue by rplansky** [leroy-merlin-br/dployer#1]
Create a configuration file in the project base path to configure deploy process. The file should follow this structure:
```json
{
    "application": "MyAwsomeApplication",
    "environment": "my-staging-env",
    "scripts": {
        "init": "composer dumpautoload",
        "another-random-event": [
            "echo 'Keep going...'", 
            "echo 'Almost there!'"
        ],
        "finish": "echo 'Nicely done! =)'"
    },
    "exclude-path": [
        "path/to/non-deployed-folder",
        "i-dont-want-to-deploy-this-file.log"
    ]
}
```

**Note:** even with `application` and `environment` keys in the configuration file, the deploy command should keep the possibility to pass this arguments as command parameters. 

**To do:**
- [x] Create sample configuration file to test.
- [x] Create class to read config keys.
- [x] Remove `required` option from `app` and `environment` arguments in deploy command
- [x] Exclude paths in the `exclude-path` key before ZIP them. 
- [x] Add support to dispatch events.
- [x] Create a class to listen the events and execute commands.
- [x] Apply key events in deploy process, i.e, `init`, `finish`, `before-pack`, `after-version-deploy`...

**Comment by Zizaco** [comment]
#2

**Comment by rplansky** [comment]
#4 - Adds simple configuration file with `application` and `environment` variables.
#5 - Excludes paths specifieds on `exclude-paths` key in configuration file.

**Comment by rplansky** [comment]
#6 - Add events to deploy process: init, before-pack, before-deploy and finish
