### ISSUE TITLE
Create new deploy tag version 1.1

### ISSUE THREAD

**Issue by rplansky** [leroy-merlin-br/dployer#11]
@Zizaco and @GuilhermeGuitte:

I think that these recent pull requests (#6, #9 and #10) resolves our actual problems.I think we can create a new version of dployer bin and tag it with version 1.1:

Main changelog:
- Added configuration file
- Moved application and environment arguments to config file
- Create events
- Configurable scripts by event
- Interactive mode
- More Verbosity

What do you guys think?

- [X] Rebuild dployer bin
- [x] Update README.md file 
- [x] Tag 1.1 version

**Comment by Zizaco** [comment]
Great! Let's do this! :smile:
